apiVersion: v1
kind: ConfigMap
metadata:
  name: user-management-dbcreation-script
data:
  mysql_usermgmt.sql: |- # creates a .sql file script
    DROP DATABASE IF EXISTS webappdb;
    CREATE DATABASE webappdb;
