apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlas-ml-inference
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: atlas-ml
  source:
    repoURL: https://github.com/RyanJKS/platform-gitops.git
    targetRevision: main
    path: clusters/azure/DEV-JKS/dev/eus2/spoke-atlas/aks-shared/applications/atlas-ml/inference
  destination:
    server: https://kubernetes.default.svc
    namespace: atlas-ml
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
