apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-policy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: platform
  source:
    repoURL: https://github.com/RyanJKS/platform-gitops.git
    targetRevision: main
    path: clusters/azure/DEV-JKS/dev/uksouth/spoke-atlas/aks-shared/platform/policy
  destination:
    server: https://kubernetes.default.svc
    namespace: atlas-ml
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
