apiVersion: v1
kind: Namespace
metadata:
  name: atlas-market
  labels:
    platform-gitops/workload: 'true'
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.30
