apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../../../catalog/platform/namespaces/base
- ../../../../../../catalog/applications/atlas-ml/namespace
components:
- ../../../../../../catalog/platform/profiles/starter/workload-namespace
