apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: platform-argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: argo-cd
      helm:
        releaseName: argocd
        valueFiles:
          - $values/catalog/platform/argocd/values.yaml
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 7.8.13
    - ref: values
      repoURL: https://github.com/RyanJKS/platform-gitops.git
      targetRevision: main
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
