appgw:
  subscriptionId: 91c6f5e9-f6ab-400c-b5e7-265fd48053d3
  resourceGroup: SANDBOX-SHARED-UKS-DEV-RGG
  name: sandboxuksdevagw
armAuth:
  identityClientID: 337789a1-2d22-47df-8085-c3570f7788f8 # TODO: Update when needed
