apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../../../../catalog/platform/defaults/argocd
  - projects/atlas-market.yaml
  - applications/platform-namespaces.yaml
  - applications/platform-policy.yaml
  - applications/atlas-market-api.yaml
  - applications/atlas-market-worker.yaml
  - projects/platform.yaml
  - applications/platform-gateway-resources.yaml
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: platform-monitoring
    patch: |
      - op: add
        path: /spec/sources/0/helm/valueFiles/-
        value: $values/clusters/azure/DEV-JKS/dev/uksouth/spoke-atlas/aks-atlas-market/platform/monitoring/values.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: platform-gateway-controller
    patch: |
      - op: add
        path: /spec/sources/0/helm/valueFiles/-
        value: $values/clusters/azure/DEV-JKS/dev/uksouth/spoke-atlas/aks-atlas-market/platform/gateway/values.yaml
