apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../../../../../catalog/applications/chaos-generator
replicas:
  - name: chaos-generator
    count: 2
images:
  - name: ryanjks/chaos-generator
    newTag: v2
