apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../../../../../catalog/platform/projects/platform
  - ../../../../../../../../../catalog/applications/atlas-ml/project
patches:
  - target:
      kind: AppProject
      name: platform
    patch: |
      - op: add
        path: /spec/destinations/-
        value:
          server: https://kubernetes.default.svc
          namespace: atlas-ml
