apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-market-api
spec:
  replicas: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: atlas-market-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: atlas-market-api
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          image: ghcr.io/ryanjks/atlas-market-api:replace-me
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
