- op: add
  path: /spec/sources/0/helm/valueFiles/-
  value: $values/catalog/platform/external-dns/azure-values.yaml
- op: add
  path: /spec/sources/0/helm/valueFiles/-
  value: $values/clusters/azure/DEV-JKS/dev/uks/sandbox/aks-agic/argocd/platform/external-dns/values.yaml
- op: add
  path: /spec/sources/1/path
  value: clusters/azure/DEV-JKS/dev/uks/sandbox/aks-agic/argocd/platform/external-dns
