serviceAccount:
  annotations:
    azure.workload.identity/client-id: c0f4156e-7473-4291-894c-60789380d6d8 # TODO: Update when needed
    azure.workload.identity/tenant-id: bac158f2-9dfe-4f66-b3e8-7fed8227d08f
domainFilters:
  - jkslabs.site
txtOwnerId: dev-uks-sandbox-aks-agic
extraArgs:
  - --azure-config-file=/etc/kubernetes/azure.json
  - --ingress-class=azure-application-gateway
