apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../../../../catalog/platform/cert-manager
  - applications/chaos-generator.yaml
  - applications/webapp-mysql-pv.yaml
