apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-generator
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: https://github.com/RyanJKS/platform-gitops.git
    targetRevision: main
    path: catalog/applications/chaos-generator
  destination:
    server: https://kubernetes.default.svc
    namespace: chaos-generator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
