apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-agic
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: platform-apps
  sources:
    - repoURL: mcr.microsoft.com/azure-application-gateway/charts
      chart: ingress-azure
      targetRevision: 1.9.1
      helm:
        releaseName: ingress-agic
        valueFiles:
          - $values/catalog/platform/ingress-agic/values.yaml
    - repoURL: https://github.com/RyanJKS/platform-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-agic
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
